# Generated by Django 5.1.1 on 2024-10-17 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyUsers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profle',
            new_name='Profile',
        ),
    ]
