# Generated by Django 5.1.1 on 2024-10-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyProducts', '0004_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('1', 'Chicken'), ('2', 'Egg')], max_length=100),
        ),
    ]
