# Generated by Django 5.1.1 on 2024-10-19 21:49
# Generated by Django 5.1.1 on 2024-10-19 21:49

from django.db import migrations


def create_initial_category(apps, schema_editor):
    Category = apps.get_model('EasyProducts', 'Category')
    if not Category.objects.filter(id=1).exists():
        Category.objects.create(id=1, name='Chicken')


class Migration(migrations.Migration):

    dependencies = [
        ('EasyProducts', '0007_product_stock'), 
    ]

    operations = [
        migrations.RunPython(create_initial_category),
    ]
