# Generated by Django 5.1.1 on 2024-10-19 21:58

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('EasyProducts', '0007_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EasyProducts.Category'),
            preserve_default=False,
        ),
    ]

