# Generated by Django 5.1.1 on 2024-10-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyProducts', '0008_auto_20241019_2349'),
        ('EasyProducts', '0009_auto_20241019_2358'),
    ]

    operations = [
    ]
